name: Check for Latest Articles

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * 1-4'  # Runs at 15:00 UTC every day-of-week from Monday through Thursday

jobs:
  update_articles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests python-dotenv feedparser chromadb langchain openai

      - name: Run the script
        id: script
        run: |
          python data.py
        shell: bash

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet; then
            echo "No changes to commit."
            echo "::set-output name=changes_exist::false"
          else
            echo "Changes detected."
            echo "::set-output name=changes_exist::true"
          fi
        shell: bash

      - name: Commit and push changes if changes exist
        if: steps.changes.outputs.changes_exist == 'true'
        run: |
          git config --global user.email "benfwalla@gmail.com"
          git config --global user.name "Ben Wallace"
          git add .
          git commit -m "Update articles: ${{ steps.script.outputs.NEW_ARTICLES }}"
          git push
